### ISSUE TITLE
Likely solution to allow you to scan multiple frequencies

### ISSUE THREAD

**Issue by jetenginesupreme** [dennyreiter/HAMaverickTempProbe#1]
Thanks for the detailed information.  I was reading about you using a different frequency and in turn losing access to other sensors.   I stumbled on to this line in the example in the rtl_433 repo and thought it would be just what you need.   

`rtl_433 -f 433.53M -f 434.02M -H 15	## Will poll two frequencies with 15 seconds hop interval.`

**Comment by dennyreiter** [comment]
That's awesome, I'll try it out.  Thank you.
